version: '3.8'

services:
  stime-api-user:
    image: registry.gitlab.com/dci-project/arqsoft-dci/proyectos/1s2024/sporttime/stime-api-user:latest
    profiles:
      - api-user
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    networks:
      - stime-network

  db:
    image: postgres:16
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB_NAME}
      POSTGRES_USER: ${POSTGRESQL_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - stime-network

volumes:
  postgres-data:

networks:
  stime-network:
    external: true